### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by marekkirejczyk** [TrueFiEng/useDApp#75]
Roadmap is a subject to change.

### 0.3 Sending transaction and notifications (published)
- [x] Address helpers #72
- [x] Sending transactions #68 
- [x] Pending transactions `useTransactions`, example [here](https://github.com/EthWorks/dapp-boilerplate/blob/master/packages/ui/src/hooks/useTransactions.ts)
- [x] Notification `useNotifications`
- [x] shortenTransactionHash & shortenIfTransactionHash

###  0.4 Misc
- [x] Persisting the connection #145
- [x] Connecting to Ganche/HardHat (automatically deploy multicall?)
- [x] useSendTransaction()
- [x] useEtherPrice()

###  0.5 Various
- [ ] Flexible chainId as part of config #47
- [ ] decodeTransaction() [151](https://github.com/EthWorks/useDApp/issues/151)
- [x] useEvents (research)
- [ ] Introduce @usedapp/tokens 
- [x] useToken() - returns Currency (immutable)
- [x] useTokenList() 
- [x] useTokenPrice() (returns currency/price)

###  0.6 Configuration 
- [x] setConfig(key, value)

### 0.10 (compatibility breaking changes)

Introduce useCalls
- [ ] Return error on invalid calls (with Multicall V2 )
- [ ] Typechain integration (experimental)

### 0.11
- [ ] Multichain support
- [ ] Hook overrides 
- [ ] useContracts()

### Future
- [ ] Extension - multichain and error handling support 
- [ ] Override refresh frequency
- [ ] Augment token lists for testnets with various tokens

**Comment by gasolin** [comment]
for 0.5 useList, could refer `useTokenList` in scaffold-eth https://github.com/austintgriffith/scaffold-eth/blob/master/packages/react-app/src/hooks/TokenList.js

**Comment by dylankilkenny** [comment]
eta on 0.3 release?

**Comment by marekkirejczyk** [comment]
@dylankilkenny 
Tomorrow or Tuesday we will publish new version (no docs)
1-2 weeks later - docs and official announcement

**Comment by gasolin** [comment]
useTokenPrice()  is done in #240 and #261 (useCoingeckoPrice/useCoingeckoTokenPrice)

**Comment by RyanRHall** [comment]
would love to see a typechain integration on the roadmap

**Comment by montanaflynn** [comment]
It seems this is now out of date.

**Comment by tt-marek** [comment]
Out of date indeed. Closing.
